accounts/urls.py
from django.urls import re_path as url
from accounts import views
# from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
    url('login/', views.Login.as_view(), name='login'),
    url('logout/', views.Logout.as_view(), name='logout'),
    url('signup/', views.SignUp.as_view(), name='signup'),
    url('activate/<uidb64>/<token>/', views.ActivateAccount.as_view(), name='activate'),
    url('password_reset/', views.PasswordReseterView.as_view(), name='password_reset'),
    url('password_reset/done/', views.PasswordReseterDoneView.as_view(), name='password_reset_done'),
    url('reset/<uidb64>/<token>/', views.PasswordReseterConfirmView.as_view(), name='password_reset_confirm'),
    url('reset/done/', views.PasswordReseterCompleteView.as_view(), name='password_reset_complete'),
    url('password_change/', views.PasswordChangerView.as_view(), name='password_change'),
    url('password_change/done/', views.PasswordChangerDoneView.as_view(), name='password_change_done'),
    url('user_edit/', views.UserEditView.as_view(), name='user_edit'),
    url('change_password/', views.change_password, name='change_password'),
    url('deleteprofile', views.deleteProfile, name='deleteprofile'),
]

eae/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'eae'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage, name='home'),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("contact/", views.contact, name="contact"),
    path("posts/", include("posts.urls")),
    path("blogs/", include("blogs.urls")),
    path('about_video/<id>', views.AboutVideoPlayer, name='about_video'),
    path('ads/', include('ads.urls', namespace='adverts')),

    path("categories/videos/local/<post_label>", views.CategoricalViewsLocalVideos.as_view(), name="categorical_views_local_videos"),
    path("categories/videos/linked/<post_label>", views.CategoricalViewsLinkedVideos.as_view(), name="categorical_views_linked_videos"),
    path("categories/blogs/<post_label>", views.CategoricalViewsBlogs.as_view(), name="categorical_view_blogs"),
    path("email_subscribtion/", views.EmailSubscriptionView, name="email_subscription"),
    path("feed_back/", views.FeedBackSubmissionView, name="feedback_submission"),
]



if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, PermissionsMixin

from django.db.models.signals import post_save
from django.dispatch import receiver 
from django.conf import settings

# Create your models here.

class User(AbstractUser, PermissionsMixin):
    address = models.CharField(max_length=100, null=True)
    def __str__(self):
        return "@{}".format(self.username)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, UserChangeForm
from django import forms
from django.contrib.auth.forms import PasswordChangeForm


class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username', 'first_name', 'last_name', 'email', 'address', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username'
        self.fields['email'].label = "Email Address"
        self.fields['address'].label = "Address"
        self.fields['password2'].label = "Confirm Password"



class UserEditForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email'}))
    address = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Address'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter First Name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Last Name'}))
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Username'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        password = self.fields.get('password')
        if password:
            password.help_text = ""    ################## Set the password change link to empty to setup your own
            password.label = ""        ################## Set the password change link to empty to setup your own

    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email', 'address']




class deleteProfileForm(UserChangeForm):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter username'}))
    password = forms.CharField(
        label=("Confirm password:"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter password'}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = "Enter your username"
        # password = self.fields.get('password')
        # if password:
        #     password.help_text = ""    ################## Set the password change link to empty to setup your own
        #     password.label = ""        ################## Set the password change link to empty to setup your own

    class Meta:
        model = get_user_model()
        fields = ['username']




##################3 Password Handler ##########################
class PasswordResetForm(PasswordResetForm):
    class Meta:
        fields = ('email')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = 'Enter email used to create the account'
        # Remember to copy how to write widgets and replace the placeholder attribute
        


##################3 Password Handler ##########################

accounts/views.py
from django.shortcuts import render, redirect
# from accounts.models import User
from django.urls import reverse_lazy #from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, View, UpdateView, DeleteView
from django.contrib.auth import views
from . import forms
from django.conf import settings

from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.sessions.backends.base import SessionBase

from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from accounts.tokens import account_activation_token
from django.contrib.auth import login
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm




User = settings.AUTH_USER_MODEL


class SignUp(View):  ## But the inheritance should be UserCreationView
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():

            user = form.save(commit=False)
            user.is_active = True # Deactivate account till it is confirmed
            user.save()

            # current_site = get_current_site(request)
            # subject = 'Activate Your ForeSight-Eritrea Account'

            # message = render_to_string('accounts/account_activation_email.html', {
            #     'user': user,
            #     'protocol': 'https' if request.is_secure() else "http",
            #     'domain': current_site.domain,
            #     'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            #     'token': account_activation_token.make_token(user),
            # })
            
            # user.email_user(subject, message)

            messages.success(request, ('We have sent you an email. Please Confirm your email to complete registration.'))

            return redirect('login')

        return render(request, self.template_name, {'form': form})



class ActivateAccount(View):
     
    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            messages.success(request, ('Your account have been confirmed.'))
            return redirect('login')
        else:
            messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))
            return redirect('login')




class UserEditView(UpdateView):
    form_class = forms.UserEditForm
    success_url = reverse_lazy('home')
    template_name = 'accounts/edit_user_profile.html.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        messages.success(request, 'Your profile has been successfully updated!')
        return super().get(request, *args, **kwargs)

    def get_object(self):
        return self.request.user




def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            # messages.success(request, 'Your password was successfully changed!')
            # return redirect('home')
            return render(request, 'index.html', {'msg_edit_pass': 'Your password was successfully changed!'})
        else:
            return render(request, 'accounts/change_password.html', {'form': form, 'err_msg': 'Please correct the error above.'})
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })


from django.contrib.auth.hashers import make_password, check_password
from .models import User as u
def deleteProfile(request):
    username = request.user.username
    password = request.user.password
    form = forms.deleteProfileForm
    result = "Nothing happened"
    if username: ### Check if username is valid and logged-in
        if request.method == 'POST':
            userprofile = u.objects.get(username = username)
            # passprofile = u.objects.get(password = password)
            # print(userprofile)
            # print(passprofile)
            # print(username)
            # print(password)
            # print(str(request.POST['username']))
            # print(check_password(str(request.POST['password']), password))
            if (str(request.POST['username']) == str(userprofile)[1:]) and (check_password(str(request.POST['password']), password)):  #### Ommit the @ simbol
                userprofile.delete()
                context = {'result': 'Your profile has been successfully deleted!'}
                return render(request, 'index.html', context)
            else:
                context = {'err_result': 'You have entered incorrect username or password. Please try again!'}
                return render(request, 'accounts/delete_profile.html', context)
    else:
        context = {'result': 'Error: Username might have already been deleted!'}
        return render(request, 'accounts/delete_profile.html', context)

    context = {'form': form}

    return render(request, 'accounts/delete_profile.html', context)




    





class Login(views.LoginView):
    template_name = 'accounts/login.html'




class Logout(views.LogoutView):
    success_url = reverse_lazy('logout')






##################### Password Reset Handler ######################

class PasswordReseterView(views.PasswordResetView):
    form_class = forms.PasswordResetForm
    email_template_name = "accounts/password_reset_email.html"
    html_email_template_name = "accounts/password_reset_email.html"
    subject_template_name = "accounts/password_reset_subject.txt"
    template_name = 'accounts/password_reset.html'
    from_email = 'resinv.pos@gmail.com'


class PasswordReseterDoneView(views.PasswordResetDoneView):
    success_url = reverse_lazy('password_reset_done')
    template_name = "accounts/password_reset_done.html"


class PasswordReseterConfirmView(views.PasswordResetConfirmView):
    success_url = reverse_lazy('password_reset_complete')
    template_name = "accounts/password_reset_confirm.html"


class PasswordReseterCompleteView(views.PasswordResetCompleteView):
    success_url = reverse_lazy('password_change_done')
    template_name = "accounts/password_reset_complete.html"

class PasswordChangerView(views.PasswordChangeView):
    success_url = reverse_lazy("password_change_done")
    template_name = "accounts/password_change_form.html"


class PasswordChangerDoneView(views.PasswordChangeDoneView):
    template_name = "accounts/password_change_done.html"




##################### Password Reset Handler ######################

accounts/templates/accounts/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

{{protocol}}://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
  Change Profile Password
{% endblock %}

{% block content %}
<div class="container">
    <h1>Change Password</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% if err_msg %}
          <link rel="stylesheet" type="text/css" href="{% static '/css_taken_from_django_core_admin/css/base.css' %}">
          <ul class="messagelist">
            <li class='error'>{{ err_msg }}</li>
          </ul>
        {% endif %}
        <input type="submit" value="Change Password" class="btn newsbox-btn m-2">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/delete_profile.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
  Delete User
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Delete User Profile</h3>
        <br>
        {% if result %}
            <link rel="stylesheet" type="text/css" href="{% static '/css_taken_from_django_core_admin/css/base.css' %}">
            <ul class="messagelist"><li class="error">{{ result }}</li></ul>
            <a href="{% url 'home' %}" class='button btn newsbox-btn m-2'>Return to home</a>
        {% endif %}
        {% if err_result %}
            <link rel="stylesheet" type="text/css" href="{% static '/css_taken_from_django_core_admin/css/base.css' %}">
            <ul class="messagelist"><li class="error">{{ err_result }}</li></ul>
            <a href="{% url 'home' %}" class='button btn newsbox-btn m-2'>Return to home</a>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <p>Inorder to delete your account, please type your Username and Password first!</p>
            {% for field in form %}
                {{ field.label }}
                {{ field }}
                <br>
            {% endfor %}
            {% if not result %}
                {% if not err_result %}
                    <input type="submit" value="Delete Account" class="btn btn-danger">
                {% endif %}
            {% endif %}
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/edit_user_profile.html.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
  Edit Profile
{% endblock %}

{% block content %}
<div class="container">
    <h2>Edit your Profile</h2>
    <br>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <p>Click <a href="{% url 'accounts:change_password' %}">here</a> if you want to change your password</p>
        <input type="submit" value="Update User" class="btn newsbox-btn m-2">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
  Login
{% endblock %}

{%block reserved_menu_item%}
	<a href="{% url 'accounts:signup' %}">Register</a>
{% endblock %}


{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <a class="btn" href="{% url 'accounts:password_reset' %}"><font size='1.5' color='AF2500'>Forgot your password</font></a>
        <br>
        <input type="submit" value="Login" class="btn newsbox-btn btn-3 m-2">
    </form>
    <br>
    <p>Don't have an account, <a href="{% url 'accounts:signup' %}">Sign up</a> here!</p>
</div>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
  Password Reset
{% endblock %}


{% block content %}
<div class="container">
    <h3>Password Reset</h3>
    <br>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Reset Password" class="btn newsbox-btn btn-3 m-2">
    </form>
    <br>
    <p>Don't have an account, <a href="{% url 'accounts:signup' %}">Sign up</a> here!</p>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
  Password Reset Successful
{% endblock %}

{% block content %}
<div class="container">
  <link rel="stylesheet" type="text/css" href="{% static '/css_taken_from_django_core_admin/css/base.css' %}">
  <ul class="messagelist">
    <li class="success">Your password has been reset successfully.  You may go ahead and click <a href="{% url 'accounts:login' %}"><u>here</u></a> to login.</li>
  </ul>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
  Confirm Password Change
{% endblock %}

{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Change Password" class="btn newsbox-btn m-2">
    </form>
    <br>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
  Password Reset
{% endblock %}


{% block content %}
<div class="container">
  <h5>Password Reset Email Sent</h5>
  <p>
    We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. 
    If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
  </p>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.
<br>
<br>
Please go to the following page and choose a new password:
<br>  
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
<br>  
<br>
Your username, in case you’ve forgotten: {{ user.get_username }}
<br>
<br>
Thanks for using our site!
<br>
<br>
<br>
The {{ site_name }} team

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
  Create Account
{% endblock %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Register" class="btn newsbox-btn m-2">
    </form>
    <br>
    <p>I already have an account, <a href="{% url 'accounts:login' %}">Login</a> here!</p>
</div>
{% endblock %}

accounts/templates/accounts/user_confirm_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
  Delete Account
{% endblock %}

{% block content %}
<div class="container">
    <h3>Delete Your User Account</h3>
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {% bootstrap_form form %}
        <input type="submit" value="Confirm" class="btn fas fa-warehouse">
    </form>
</div>
{% endblock %}