accounts/urls.py
from django.urls import re_path as url
from accounts import views
# from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
    url('login/', views.Login.as_view(), name='login'),
    url('logout/', views.Logout.as_view(), name='logout'),
    url('signup/', views.SignUp.as_view(), name='signup'),
    url('activate/<uidb64>/<token>/', views.ActivateAccount.as_view(), name='activate'),
    url('password_reset/', views.PasswordReseterView.as_view(), name='password_reset'),
    url('password_reset/done/', views.PasswordReseterDoneView.as_view(), name='password_reset_done'),
    url('reset/<uidb64>/<token>/', views.PasswordReseterConfirmView.as_view(), name='password_reset_confirm'),
    url('reset/done/', views.PasswordReseterCompleteView.as_view(), name='password_reset_complete'),
    url('password_change/', views.PasswordChangerView.as_view(), name='password_change'),
    url('password_change/done/', views.PasswordChangerDoneView.as_view(), name='password_change_done'),
    url('user_edit/', views.UserEditView.as_view(), name='user_edit'),
    url('change_password/', views.change_password, name='change_password'),
    url('deleteprofile', views.deleteProfile, name='deleteprofile'),
]

blogs/urls.py
from django.urls import re_path as url
from . import views

app_name = 'blogs'

urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^your_posts/$', views.PostsByYouOnly.as_view(), name='posts_by_you_only'),
    url(r'^your_published_posts/$', views.PostsPublishedByYouOnly.as_view(), name='posts_pub_by_you_only'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^search/$', views.BlogSearch, name='blog_search'),
]

eae/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'eae'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage, name='home'),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("contact/", views.contact, name="contact"),
    path("posts/", include("posts.urls")),
    path("blogs/", include("blogs.urls")),
    path('about_video/<id>', views.AboutVideoPlayer, name='about_video'),
    path('ads/', include('ads.urls', namespace='adverts')),

    path("categories/videos/local/<post_label>", views.CategoricalViewsLocalVideos.as_view(), name="categorical_views_local_videos"),
    path("categories/videos/linked/<post_label>", views.CategoricalViewsLinkedVideos.as_view(), name="categorical_views_linked_videos"),
    path("categories/blogs/<post_label>", views.CategoricalViewsBlogs.as_view(), name="categorical_view_blogs"),
    path("email_subscribtion/", views.EmailSubscriptionView, name="email_subscription"),
    path("feed_back/", views.FeedBackSubmissionView, name="feedback_submission"),
]



if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import re_path as url
from . import views
from django.urls import path
from management.models import HomeView

app_name = "posts"

urlpatterns = [
    path("", views.Posts, name="posts"),
    path("videos/", views.Videos, name="videos"),

    path("videos/linked_video_player/<id>", views.LinkedVideoPlayer, name="linked_video_player"),
    path("videos/local_video_player/<id>", views.LocalVideoPlayer, name="local_video_player"),

    path("videos/search/linked/", views.VideosSearch, name="video_search"),
    # path("videos/search/linked/", views.LinkedVideosSearch, name="linked_video_search"),
    # path("videos/search/local/", views.LocalVideosSearch, name="local_video_search"),
    path('videos/txt_edit/<id>', views.VideosTxtEditor, name="text_editor"),
]

blogs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from blogs.models import Post, Comment
from django.utils import timezone
from blogs.forms import PostForm, CommentForm

from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings


from .models import User


per_page = 2

class PostListView(ListView):
    paginate_by = per_page
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin,CreateView):
    #login_url = 'accounts/login/'
    #redirect_field_name = 'blogs/post_detail.html'

    form_class = PostForm

    model = Post

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)



class PostUpdateView(LoginRequiredMixin,UpdateView):
    #login_url = 'accounts/login/'
    #redirect_field_name = 'blogs/post_detail.html'

    form_class = PostForm

    model = Post


class DraftListView(LoginRequiredMixin,ListView):
    #login_url = 'accounts/login/'
    #redirect_field_name = 'blogs/post_draft_list.html'

    paginate_by = per_page
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True, created_by=User(self.request.user.pk)).order_by('-created_date')


class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('blogs:post_list')

#######################################
## Functions that require a pk match ##
#######################################

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blogs:post_detail', pk=pk)

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        form.instance.created_by = request.user
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blogs:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blogs/comment_form.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blogs:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blogs:post_detail', pk=post_pk)


# @login_required
# def PostsByYouOnly(request):

#     your_post = Post.objects.order_by('-created_date')

#     your_post = Paginator(your_post, paginator)
#     page = request.GET.get('page')
#     your_post = your_post.get_page(page)

#     return render(request, 'blogs/post_list.html', {'your_post': your_post})
class PostsByYouOnly(ListView):
    paginate_by = per_page
    model = Post

    def get_queryset(self):
        return Post.objects.filter(created_date__lte=timezone.now(), created_by=User(self.request.user.pk)).order_by('-created_date')


# @login_required
# def PostsPublishedByYouOnly(request):

#     your_published_post = Post.objects.filter(published_date__isnull=False).order_by('-published_date')

#     your_published_post = Paginator(your_published_post, paginator)
#     page = request.GET.get('page')
#     your_published_post = your_published_post.get_page(page)

#     return render(request, 'blogs/post_list.html', {'your_published_post': your_published_post})
class PostsPublishedByYouOnly(ListView):
    paginate_by = per_page
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=False, created_by=User(self.request.user.pk)).order_by('-published_date')


def BlogSearch(request):

    context = {}

    if request.method == 'POST':
        search_value = request.POST['search']
        
        blog_search_result = Post.objects.filter(title__icontains=search_value, published_date__isnull=False).order_by('-published_date')
                
        found = len(blog_search_result)

        paginator = Paginator(blog_search_result, 100) #per_page) # Remember to include page number e.g. , 6
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
        'page_obj': page_obj, 
        'found': found
        }
        return render(request, 'blogs/post_list.html', context)
    
    # return render(request, 'blogs/post_list.html', context)

# class BlogSearch(ListView):
#     def get_queryset(self):
#         return Post.objects.filter(title__icontains=self.request.POST['search_value'], published_date__isnull=False).order_by('-published_date')
    

                
            

posts/views.py
from django.views.generic import TemplateView
from datetime import datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from management.models import PostsPage
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from posts.models import LinkedVideos, LocalVideos
from management.models import ManualAdsManager

# Create your views here.

per_page = 3

def Posts(request):
    cover_page = PostsPage.objects.order_by('-created_at')[0:1]
    context = {'cover_page':cover_page}
    return render(request, 'posts/posts.html', context)




def Videos(request):
    
    linked_video_listings = LinkedVideos.objects.order_by('-published_date')
    local_video_listings = LocalVideos.objects.order_by('-published_date')

    paginator1 = Paginator(linked_video_listings, per_page)
    paginator2 = Paginator(local_video_listings, per_page)

    page = request.GET.get('page')

    paged_listing1 = paginator1.get_page(page)
    paged_listing2 = paginator2.get_page(page)

    side_ad = ManualAdsManager.objects.filter(ad_category='side').order_by('-added_date')[0:1]
    bottom_ad = ManualAdsManager.objects.filter(ad_category='bottom').order_by('-added_date')[0:1]
 
    context = {
                'linked_video_listings':paged_listing1,
                'local_video_listings': paged_listing2,
                'side_ad': side_ad,
                'bottom_ad': bottom_ad
                }

    return render(request, 'posts/videos.html', context)


@login_required
def LinkedVideoPlayer(request, id):

    linked_video_single = get_object_or_404(LinkedVideos, pk=id)
    linked_video_single_url = str(linked_video_single.link)
    linked_video_single_url = linked_video_single_url[:20] + linked_video_single_url[26:]
    linked_video_single_url = linked_video_single_url[:15] + linked_video_single_url[19:]
    linked_video_single_url = linked_video_single_url[:13] + ".be" + linked_video_single_url[15:]
    print(linked_video_single_url)
    sidebar_related_videos = LinkedVideos.objects.filter(post_label=linked_video_single.post_label).order_by('-published_date')
    side_ad = ManualAdsManager.objects.filter(ad_category='side').order_by('-added_date')[0:1]
    bottom_ad = ManualAdsManager.objects.filter(ad_category='bottom').order_by('-added_date')[0:1]

    context = {
    'linked_video_single': linked_video_single,
    'side_ad': side_ad,
    'bottom_ad': bottom_ad,
    'sidebar_related_videos': sidebar_related_videos,
    'linked_video_single_url': linked_video_single_url
    }

    return render(request, 'posts/linked_video_player.html', context)

@login_required
def LocalVideoPlayer(request, id):

    local_video_single = get_object_or_404(LocalVideos, pk=id)
    sidebar_related_videos = LocalVideos.objects.filter(post_label=local_video_single.post_label).order_by('-published_date')
    side_ad = ManualAdsManager.objects.filter(ad_category='side').order_by('-added_date')[0:1]
    bottom_ad = ManualAdsManager.objects.filter(ad_category='bottom').order_by('-added_date')[0:1]

    context = {
    'local_video_single': local_video_single,
    'side_ad': side_ad,
    'bottom_ad': bottom_ad,
    'sidebar_related_videos': sidebar_related_videos
    }

    return render(request, 'posts/local_video_player.html', context)


'''


def LinkedVideosSearch(request):
    search_value = request.POST['search']
    flag = 'flag'
    linked_search_result = LinkedVideos.objects.filter(title__icontains=search_value).order_by('-published_date')
    
    found = len(linked_search_result)

    paginator = Paginator(linked_search_result, 6)
    page = request.GET.get('page')
    linked_paged_search_listing = paginator.get_page(page)

    context = {
    'linked_paged_search_listing': linked_paged_search_listing, 
    'flag': flag, 
    'found': found
    }
    return render(request, 'posts/videos.html', context)



def LocalVideosSearch(request):
    search_value = request.POST['search']
    flag = 'flag'
    local_search_result = LinkedVideos.objects.filter(title__icontains=search_value).order_by('-published_date')
    
    found = len(local_search_result)

    paginator = Paginator(local_search_result, 6)
    page = request.GET.get('page')
    local_paged_search_listing = paginator.get_page(page)

    context = {
    'local_paged_search_listing': local_paged_search_listing, 
    'flag': flag, 
    'found': found
    }
    return render(request, 'posts/videos.html', context)


'''



def VideosSearch(request):

    flag = "flag"

    if request.method == 'POST':
        search_value = request.POST['search']
        video_type = request.POST['video_type']
        context = {}
        if video_type == 'linked':
                
            linked_search_result = LinkedVideos.objects.filter(title__icontains=search_value).order_by('-published_date')
                
            found = len(linked_search_result)

            paginator = Paginator(linked_search_result, int(found)+1) # Remember to include page number e.g. , 6
            page = request.GET.get('page')
            linked_paged_search_listing = paginator.get_page(page)

            context = {
            'linked_paged_search_listing': linked_paged_search_listing, 
            'flag': flag, 
            'found': found
            }

        elif video_type == 'local':
                
            local_search_result = LocalVideos.objects.filter(title__icontains=search_value).order_by('-published_date')

            found = len(local_search_result)

            paginator = Paginator(local_search_result, int(found)+1) # Remember to include page number e.g. , 6
            page = request.GET.get('page')
            local_paged_search_listing = paginator.get_page(page)

            context = {
            'local_paged_search_listing': local_paged_search_listing, 
            'flag': flag, 
            'found': found
            }

        return render(request, 'posts/videos.html', context)




def VideosTxtEditor(request, id):

    linked_video_single = get_object_or_404(LinkedVideos, pk=id)
    linked_video_single_url = str(linked_video_single.link)
    linked_video_single_url = linked_video_single_url[:20] + linked_video_single_url[26:]
    linked_video_single_url = linked_video_single_url[:15] + linked_video_single_url[19:]
    linked_video_single_url = linked_video_single_url[:13] + ".be" + linked_video_single_url[15:]
    sidebar_related_videos = LinkedVideos.objects.filter(post_label=linked_video_single.post_label).order_by('-published_date')
    side_ad = ManualAdsManager.objects.filter(ad_category='side').order_by('-added_date')[0:1]
    bottom_ad = ManualAdsManager.objects.filter(ad_category='bottom').order_by('-added_date')[0:1]

    context = {
    'linked_video_single': linked_video_single,
    'side_ad': side_ad,
    'bottom_ad': bottom_ad,
    'sidebar_related_videos': sidebar_related_videos,
    'linked_video_single_url': linked_video_single_url
    }

    if request.method == 'POST':
        txt = request.POST['txt_editor']
        print(txt)
        LinkedVideos.objects.filter(pk=id).update(text=txt)

    return render(request, 'posts/linked_video_player.html', context)

        

blogs/templates/blogs/blog_base.html
{% extends "base.html" %}

{% load static %}



{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'blog_css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'blog_css/site.css' %}" />
    <script src="{% static 'js/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
	<script src="{% static 'js/respond.js' %}"></script>

<div class="hero-area">
	<!-- Hero Post Slides -->
    <div class="hero-post-slides owl-carousel">
        <!-- Single Slide -->
        <div class="single-slide">
            <div class="container-fluid">
				<div class="row">
					<div class="col-12 col-md-12">
					   	{% block pregroup %}{% endblock %}
					    {% block group_content %}{% endblock %}
					    {% block postgroup %}{% endblock %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

blogs/templates/blogs/comment_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}
  Add Comment
{% endblock %}


{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <!-- Post Details Content Area -->
        <div class="col-12 col-lg-8">
        	<h4>Post Comment  to selected blog</h4>
        	<form method="POST" class="post-form">
        		{% csrf_token %}
        		{{form.as_p}}
        		<button type="submit" class="btn btn-primary btn-outline-primary px-4 py-3">Post Comment</button>
        	</form>
        </div> 

  		<!-- Sidebar Widget -->
		<div class="col-12 col-sm-9 col-md-6 col-lg-4">
         	    <div class="sidebar-area">
         	        <!-- Add Widget -->
         	        <div class="single-widget-area add-widget mb-30">
         	            <a href="#">
         	                <img src="{% static 'img/bg-img/add3.png' %}" alt="">
         	            </a>
         	        </div>

         	        <!-- Latest News Widget -->
         	        <div class="single-widget-area news-widget mb-30">
         	            <h4>Latest News</h4>

         	            <!-- Single News Area -->
         	            <div class="single-blog-post d-flex style-4 mb-30">
         	                <!-- Blog Thumbnail -->
         	                <div class="blog-thumbnail">
         	                    <a href="#"><img src="{% static 'img/bg-img/16.jpg' %}" alt=""></a>
         	                </div>

         	                <!-- Blog Content -->
         	                <div class="blog-content">
         	                    <span class="post-date">June 20, 2018</span>
         	                    <a href="#" class="post-title">Nearly a quarter have no emergency savings</a>
         	                </div>
         	            </div>

         	            <!-- Single News Area -->
         	            <div class="single-blog-post d-flex style-4 mb-30">
         	                <!-- Blog Thumbnail -->
         	                <div class="blog-thumbnail">
         	                    <a href="#"><img src="{% static 'img/bg-img/17.jpg' %}" alt=""></a>
         	                </div>

         	                <!-- Blog Content -->
         	                <div class="blog-content">
         	                    <span class="post-date">June 20, 2018</span>
         	                    <a href="#" class="post-title">Nearly a quarter have no emergency savings</a>
         	                </div>
         	            </div>

         	            <!-- Single News Area -->
         	            <div class="single-blog-post d-flex style-4 mb-30">
         	                <!-- Blog Thumbnail -->
         	                <div class="blog-thumbnail">
         	                    <a href="#"><img src="{% static 'img/bg-img/18.jpg' %}" alt=""></a>
         	                </div>

         	                <!-- Blog Content -->
         	                <div class="blog-content">
         	                    <span class="post-date">June 20, 2018</span>
         	                    <a href="#" class="post-title">Top bitcoin exchange says over $30 million stolen</a>
         	                </div>
         	            </div>

         	            <!-- Single News Area -->
         	            <div class="single-blog-post d-flex style-4 mb-30">
         	                <!-- Blog Thumbnail -->
         	                <div class="blog-thumbnail">
         	                    <a href="#"><img src="{% static 'img/bg-img/19.jpg' %}" alt=""></a>
         	                </div>

         	                <!-- Blog Content -->
         	                <div class="blog-content">
         	                    <span class="post-date">June 20, 2018</span>
         	                    <a href="#" class="post-title">Top bitcoin exchange says over $30 million stolen</a>
         	                </div>
         	            </div>

         	            <!-- Single News Area -->
         	            <div class="single-blog-post d-flex style-4 mb-30">
         	                <!-- Blog Thumbnail -->
         	                <div class="blog-thumbnail">
         	                    <a href="#"><img src="{% static 'img/bg-img/20.jpg' %}" alt=""></a>
         	                </div>

         	                <!-- Blog Content -->
         	                <div class="blog-content">
         	                    <span class="post-date">June 20, 2018</span>
         	                    <a href="#" class="post-title">Dow falls 287 points as trade war fears escalate</a>
         	                </div>
         	            </div>
         	        </div>
         	    </div>
         	</div>      
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/post_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block title %}
  Confirm Post Removal
{% endblock %}


{% block content %}
	


	<section class="post-news-area section-padding-70-0 mb-70">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Post Details Content Area -->
                <div class="col-50 col-lg-12">
                    <div class="post-details-content mb-100">
                        <div>
                          <p>
                            <h3>Are you sure you want to delete the post, "{{ object }}"?</h3>
                            <br>
							<h5 class="mb-4">Confirm Post Removal</h5>
							<!--<p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>-->
							<form action="" method="post">{% csrf_token %}
							  <input class='btn btn-danger' type="submit" value="Confirm" />
							</form>
                          </p>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

blogs/templates/blogs/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Blog Detail
{% endblock %}

{% block content %}
  <!-- ##### Post Details Title Area Start ##### -->
    <div class="post-details-title-area bg-overlay clearfix" style="background-image: url({{ post.blog_cover_image.url }})">
        <div class="container-fluid h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12 col-lg-8">
                    <!-- Post Content -->
                    <div class="post-content">
                        <p class="tag"><span>{{ post.post_quote }}</span></p>
                        <p class="post-title">{{ post.title }}</p>
                        <span class="post-date">{{ post.author | upper }}</span>
                        <div class="d-flex align-items-center">
                          {% if post.published_date %}
                            <span class="post-date mr-30">
                                {{ post.published_date | date }}
                            </span>
                            </div>
                          {% else %}
                            <span class="post-date mr-30">
                                Not Published
                            </span>
                          {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Post Details Title Area End ##### -->

    <!-- ##### Post Details Area Start ##### -->
    <section class="post-news-area section-padding-100-0 mb-70">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Post Details Content Area -->
                <div class="col-12 col-lg-8">
                    <div class="post-details-content mb-100">
                        <div>
                          <p>
                            <p class='postcontent'>{{ post.text|safe|linebreaksbr }}</p>
                            {% if post.published_date %}
                                <div class="date postdate">
                                    {{ post.author | upper }}
                                    <br>
                                    {{ post.published_date | date }}
                                </div>
                            {% else %}
                                <a href="{% url 'blogs:post_publish' pk=post.pk %}" class="btn btn-primary btn-outline-primary px-4 py-3">Publish</a>
                            {% endif %}
                            <br>
                            <br>
                            {% if user.is_authenticated and user == post.created_by %}
                                <a class="btn btn-secondary" href="{% url 'blogs:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil">Edit Post</span></a>
                                <a class="btn btn-secondary" href="{% url 'blogs:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove">Remove Post</span></a>
                            {% endif %}
                          </p>
                      </div>
                      <hr>
                    </div>


                    <!-- Comment Area Start -->
                    <div class="comment_area clearfix mb-100">
                        <ol>
                            <!-- Single Comment Area -->
                            {% for comment in post.comments.all %}
                                {% if user.is_authenticated or comment.approved_comments %}
                                    <li class="single_comment_area">
                                        <!-- Comment Content -->
                                        <div class="comment-content d-flex">
                                            <!-- Comment Author -->
                                            <!--
                                            <div class="comment-author">
                                                <img src="{% static 'img/bg-img/32.jpg' %}" alt="author">
                                            </div>
                                            -->
                                            <!-- Comment Meta -->
                                            <div class="comment-meta">
                                                <div class="d-flex">
                                                    <a href="#">{{ comment.created_by.first_name }} {{ comment.created_by.last_name }}</a>
                                                </div>
                                                <p>{{ comment.text|safe|linebreaks }}</p>
                                                <p>{{ comment.created_date }}</p>
                                                {% if not comment.approved_comments %}
                                                    {% if user.is_authenticated and user == comment.created_by %}
                                                        <a href="{% url 'blogs:comment_remove' pk=comment.pk %}" class="btn"><font color="red">Remove</font></a>
                                                        <a href="{% url 'blogs:comment_approve' pk=comment.pk %}" class="btn"><font color="blue">Approve</font></a>
                                                    {% endif %}
                                                {% endif %}
                                            </div>
                                        </div>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ol>
                        <br>
                        <a class="btn btn-primary btn-comment" href="{% url 'blogs:add_comment_to_post' pk=post.pk %}">Comment</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Post Details Area End ##### -->


{% endblock %}

blogs/templates/blogs/post_form.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block title %}
  New Blog
{% endblock %}


{% block content %}
	<div class="container">
        <div class="row justify-content-center">
            <!-- Post Details Content Area -->
            <div class="col-12 col-lg-8">
				<h2 class="mb-4">Create New Blog</h2>
				<br>
				<!--<p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>-->
				<form  enctype="multipart/form-data" method="POST">
			        {% csrf_token %}
					{{ form.as_p }}
					<button type="submit" class="btn btn-primary btn-outline-primary px-4 py-3 buttonLabels">Create Post</button>
				</form>
			</div>
            <!-- Sidebar Widget -->
            
        </div>
    </div>
{% endblock %}