blogs/urls.py
from django.urls import re_path as url
from . import views

app_name = 'blogs'

urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^your_posts/$', views.PostsByYouOnly.as_view(), name='posts_by_you_only'),
    url(r'^your_published_posts/$', views.PostsPublishedByYouOnly.as_view(), name='posts_pub_by_you_only'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^search/$', views.BlogSearch, name='blog_search'),
]

eae/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'eae'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage, name='home'),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("contact/", views.contact, name="contact"),
    path("posts/", include("posts.urls")),
    path("blogs/", include("blogs.urls")),
    path('about_video/<id>', views.AboutVideoPlayer, name='about_video'),
    path('ads/', include('ads.urls', namespace='adverts')),

    path("categories/videos/local/<post_label>", views.CategoricalViewsLocalVideos.as_view(), name="categorical_views_local_videos"),
    path("categories/videos/linked/<post_label>", views.CategoricalViewsLinkedVideos.as_view(), name="categorical_views_linked_videos"),
    path("categories/blogs/<post_label>", views.CategoricalViewsBlogs.as_view(), name="categorical_view_blogs"),
    path("email_subscribtion/", views.EmailSubscriptionView, name="email_subscription"),
    path("feed_back/", views.FeedBackSubmissionView, name="feedback_submission"),
]



if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import re_path as url
from . import views
from django.urls import path
from management.models import HomeView

app_name = "posts"

urlpatterns = [
    path("", views.Posts, name="posts"),
    path("videos/", views.Videos, name="videos"),

    path("videos/linked_video_player/<id>", views.LinkedVideoPlayer, name="linked_video_player"),
    path("videos/local_video_player/<id>", views.LocalVideoPlayer, name="local_video_player"),

    path("videos/search/linked/", views.VideosSearch, name="video_search"),
    # path("videos/search/linked/", views.LinkedVideosSearch, name="linked_video_search"),
    # path("videos/search/local/", views.LocalVideosSearch, name="local_video_search"),
    path('videos/txt_edit/<id>', views.VideosTxtEditor, name="text_editor"),
]

posts/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from embed_video.fields import EmbedVideoField

# Create your models here.
from django.contrib.auth import get_user_model
User = get_user_model()


class LinkedVideos(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    link = EmbedVideoField()
    image = models.ImageField(upload_to='img', blank=False)
    published_date = models.DateTimeField(default=timezone.now)

    post_label_choices = [
    ('er_hist', 'Eritrean Histories'),
    ('er_cult', 'Eritrean Culture'),
    ('er_polt', 'Politics'),
    ('er_peop', 'People'),
    ('er_tech', 'Technology'),
    ('other', 'Other'),
    ]
    post_label = models.CharField(max_length=200, null=True, blank=True, choices=post_label_choices)

    def __str__(self):
        return self.title


class LocalVideos(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    local_video_file = models.FileField(upload_to='local_videos', blank=False, default="")
    image = models.ImageField(upload_to='img', blank=True)
    published_date = models.DateTimeField(default=timezone.now)

    post_label_choices = [
    ('er_hist', 'Eritrean Histories'),
    ('er_cult', 'Eritrean Culture'),
    ('er_polt', 'Politics'),
    ('er_peop', 'People'),
    ('er_tech', 'Technology'),
    ('other', 'Other'),
    ]
    post_label = models.CharField(max_length=200, null=True, blank=True, choices=post_label_choices)

    def __str__(self):
        return self.title

posts/views.py
from django.views.generic import TemplateView
from datetime import datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from management.models import PostsPage
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from posts.models import LinkedVideos, LocalVideos
from management.models import ManualAdsManager

# Create your views here.

per_page = 3

def Posts(request):
    cover_page = PostsPage.objects.order_by('-created_at')[0:1]
    context = {'cover_page':cover_page}
    return render(request, 'posts/posts.html', context)




def Videos(request):
    
    linked_video_listings = LinkedVideos.objects.order_by('-published_date')
    local_video_listings = LocalVideos.objects.order_by('-published_date')

    paginator1 = Paginator(linked_video_listings, per_page)
    paginator2 = Paginator(local_video_listings, per_page)

    page = request.GET.get('page')

    paged_listing1 = paginator1.get_page(page)
    paged_listing2 = paginator2.get_page(page)

    side_ad = ManualAdsManager.objects.filter(ad_category='side').order_by('-added_date')[0:1]
    bottom_ad = ManualAdsManager.objects.filter(ad_category='bottom').order_by('-added_date')[0:1]
 
    context = {
                'linked_video_listings':paged_listing1,
                'local_video_listings': paged_listing2,
                'side_ad': side_ad,
                'bottom_ad': bottom_ad
                }

    return render(request, 'posts/videos.html', context)


@login_required
def LinkedVideoPlayer(request, id):

    linked_video_single = get_object_or_404(LinkedVideos, pk=id)
    linked_video_single_url = str(linked_video_single.link)
    linked_video_single_url = linked_video_single_url[:20] + linked_video_single_url[26:]
    linked_video_single_url = linked_video_single_url[:15] + linked_video_single_url[19:]
    linked_video_single_url = linked_video_single_url[:13] + ".be" + linked_video_single_url[15:]
    print(linked_video_single_url)
    sidebar_related_videos = LinkedVideos.objects.filter(post_label=linked_video_single.post_label).order_by('-published_date')
    side_ad = ManualAdsManager.objects.filter(ad_category='side').order_by('-added_date')[0:1]
    bottom_ad = ManualAdsManager.objects.filter(ad_category='bottom').order_by('-added_date')[0:1]

    context = {
    'linked_video_single': linked_video_single,
    'side_ad': side_ad,
    'bottom_ad': bottom_ad,
    'sidebar_related_videos': sidebar_related_videos,
    'linked_video_single_url': linked_video_single_url
    }

    return render(request, 'posts/linked_video_player.html', context)

@login_required
def LocalVideoPlayer(request, id):

    local_video_single = get_object_or_404(LocalVideos, pk=id)
    sidebar_related_videos = LocalVideos.objects.filter(post_label=local_video_single.post_label).order_by('-published_date')
    side_ad = ManualAdsManager.objects.filter(ad_category='side').order_by('-added_date')[0:1]
    bottom_ad = ManualAdsManager.objects.filter(ad_category='bottom').order_by('-added_date')[0:1]

    context = {
    'local_video_single': local_video_single,
    'side_ad': side_ad,
    'bottom_ad': bottom_ad,
    'sidebar_related_videos': sidebar_related_videos
    }

    return render(request, 'posts/local_video_player.html', context)


'''


def LinkedVideosSearch(request):
    search_value = request.POST['search']
    flag = 'flag'
    linked_search_result = LinkedVideos.objects.filter(title__icontains=search_value).order_by('-published_date')
    
    found = len(linked_search_result)

    paginator = Paginator(linked_search_result, 6)
    page = request.GET.get('page')
    linked_paged_search_listing = paginator.get_page(page)

    context = {
    'linked_paged_search_listing': linked_paged_search_listing, 
    'flag': flag, 
    'found': found
    }
    return render(request, 'posts/videos.html', context)



def LocalVideosSearch(request):
    search_value = request.POST['search']
    flag = 'flag'
    local_search_result = LinkedVideos.objects.filter(title__icontains=search_value).order_by('-published_date')
    
    found = len(local_search_result)

    paginator = Paginator(local_search_result, 6)
    page = request.GET.get('page')
    local_paged_search_listing = paginator.get_page(page)

    context = {
    'local_paged_search_listing': local_paged_search_listing, 
    'flag': flag, 
    'found': found
    }
    return render(request, 'posts/videos.html', context)


'''



def VideosSearch(request):

    flag = "flag"

    if request.method == 'POST':
        search_value = request.POST['search']
        video_type = request.POST['video_type']
        context = {}
        if video_type == 'linked':
                
            linked_search_result = LinkedVideos.objects.filter(title__icontains=search_value).order_by('-published_date')
                
            found = len(linked_search_result)

            paginator = Paginator(linked_search_result, int(found)+1) # Remember to include page number e.g. , 6
            page = request.GET.get('page')
            linked_paged_search_listing = paginator.get_page(page)

            context = {
            'linked_paged_search_listing': linked_paged_search_listing, 
            'flag': flag, 
            'found': found
            }

        elif video_type == 'local':
                
            local_search_result = LocalVideos.objects.filter(title__icontains=search_value).order_by('-published_date')

            found = len(local_search_result)

            paginator = Paginator(local_search_result, int(found)+1) # Remember to include page number e.g. , 6
            page = request.GET.get('page')
            local_paged_search_listing = paginator.get_page(page)

            context = {
            'local_paged_search_listing': local_paged_search_listing, 
            'flag': flag, 
            'found': found
            }

        return render(request, 'posts/videos.html', context)




def VideosTxtEditor(request, id):

    linked_video_single = get_object_or_404(LinkedVideos, pk=id)
    linked_video_single_url = str(linked_video_single.link)
    linked_video_single_url = linked_video_single_url[:20] + linked_video_single_url[26:]
    linked_video_single_url = linked_video_single_url[:15] + linked_video_single_url[19:]
    linked_video_single_url = linked_video_single_url[:13] + ".be" + linked_video_single_url[15:]
    sidebar_related_videos = LinkedVideos.objects.filter(post_label=linked_video_single.post_label).order_by('-published_date')
    side_ad = ManualAdsManager.objects.filter(ad_category='side').order_by('-added_date')[0:1]
    bottom_ad = ManualAdsManager.objects.filter(ad_category='bottom').order_by('-added_date')[0:1]

    context = {
    'linked_video_single': linked_video_single,
    'side_ad': side_ad,
    'bottom_ad': bottom_ad,
    'sidebar_related_videos': sidebar_related_videos,
    'linked_video_single_url': linked_video_single_url
    }

    if request.method == 'POST':
        txt = request.POST['txt_editor']
        print(txt)
        LinkedVideos.objects.filter(pk=id).update(text=txt)

    return render(request, 'posts/linked_video_player.html', context)

        

posts/templates/posts/linked_video_player.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% load static %}
{% load bootstrap4 %}

{% block title %}
	{{ linked_video_single.title }}
{% endblock %}

{% block content %}

	<!-- ##### Intro News Area Start ##### -->
	<section class="intro-news-area section-padding-100-0 mb-70">
	    <div class="container">
	        <div class="row justify-content-center">
	            <!-- Intro News Tabs Area -->
	            <div class="col-12 col-lg-9">
	            	<br>
	            	<form action="{% url 'posts:video_search' %}" method="POST">
	            	    {% csrf_token %}
	            	    <table border="0" class="col-12">
	            	        <tr>
	            	            <td>
	            	                <input type="text" name="search" class="form-control col-12 col-lg-12" placeholder="Search selected source by keyword..." value="" required>
	            	            </td>
	            	            <td>
	            	                <select name="video_type" class="form-control col-12 col-lg-10" required>
	            	                    <option value="">Select source</option>
	            	                    <option value="">-----------</option>
	            	                    <option value="linked">Linked Videos</option>
	            	                    <option value="local">Local Videos</option>
	            	                </select>
	            	            </td>
	            	            <td>
	            	                <input type="submit" value="Search" class="btn btn-primary col-12 col-lg-9">
	            	            <td>
	            	        </tr>
	            	    </table>
	            	</form>
	            	<br>
	            	<br>
	                <div class="intro-news-tab">
	                	<!-- Intro News Filter -->
	                	<div class="intro-news-filter d-flex justify-content-between">
	                	    	{% if linked_video_single %}
	                	    		<h3>{{ linked_video_single.title }}</h3>
	                	    	{% endif %}
	                	    <nav>
	                	        <div class="nav nav-tabs" id="nav-tab" role="tablist">
	                	            <a class="nav-item nav-link active" href="{{ linked_video_single_url }}" target="_blank" role="tab" aria-controls="nav-1" aria-selected="true">View from Youtube</a>
	                	            <a class="nav-item nav-link active" href="{% url 'posts:videos' %}" role="tab" aria-controls="nav-1" aria-selected="true">Videos Home</a>
	                	        </div>
	                	    </nav>
	                	</div>

	                    <div class="tab-content" id="nav-tabContent">
	                    	{% if linked_video_single %}
	                    		<iframe width="820" height="470" src="{{ linked_video_single.link }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
						       	<p>{{ linked_video_single.text|safe|linebreaksbr  }}</p>
						       	{% if user == linked_video_single.author %}
						       		<form method="POST" action="{% url 'posts:text_editor' linked_video_single.id %}">
						       			{% csrf_token %}
						       			<textarea class="editable medium-editor-textarea" name="txt_editor" value="Everything will be fine" required="true"></textarea>
						       			<span class="glyphicon glyphicon-plus-sign"><input type="submit" value="Edit & Post text" class="btn-primary buttonLabels"></span> 
						       		</form>
						       	{% endif %}
							{% else %}
								<h3><font color="red">Sorry, this video is unavailable!</font></h3>
							{% endif %}
	                    </div>
	                </div>
	            </div>

	            <!-- Sidebar Widget -->
	            <div class="col-12 col-sm-9 col-md-6 col-lg-3">
	            	<!-- Add Widget -->
                    <div class="single-widget-area add-widget mb-30">
                    	<!-- Single News Area -->
                    	{% if sidebar_related_videos %}
                    		{% for side_video in sidebar_related_videos %}
                    			{% if forloop.counter <= 10 %}
			                    	<div class="single-blog-post style-2 mb-5">
			                    	    <!-- Blog Thumbnail -->
			                    	    <div class="blog-thumbnail">
			                    	        <a href="{% url 'posts:local_video_player' side_video.id %}"><img src="{{ side_video.image.url }}" alt=""></a>
			                    	    </div>

			                    	    <!-- Blog Content -->
			                    	    <div class="blog-content">
                                            <span class="post-date">{{ side_video.published_date|date:"F j, Y" }}</span>
                                             <a href="{% url 'posts:local_video_player' side_video.id %}" class="post-title video-btn">{{ side_video.title }}</a>
                                            <a href="{% url 'posts:local_video_player' side_video.id %}" class="post-author video-btn">By {{ side_video.author }}</a>
                                        </div>
			                    	</div>
			            		{% endif %}
                        	{% endfor %}
                        {% endif %}
                    </div>
	            </div>
	        </div>
	    </div>
	</section>
	<!-- ##### Intro News Area End ##### -->
	 <!-- ##### Add Area Start ##### -->
    <div class="big-add-area mb-100">
        <div class="container-fluid">
            {% if bottom_ad %}
                {% for i in bottom_ad %}
                    <a href="{{ i.ad_link }}">
                        <img src="{{ i.ad.url }}" alt="">
                    </a>
                {% endfor %}
            {% endif %}
        </div>
    </div>

{% endblock %}

posts/templates/posts/local_video_player.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% load static %}

{% block title %}
	{{ local_video_single.title }}
{% endblock %}

{% block content %}

	<!-- ##### Intro News Area Start ##### -->
	<section class="intro-news-area section-padding-100-0 mb-70">
	    <div class="container">
	        <div class="row justify-content-center">
	            <!-- Intro News Tabs Area -->
	            <div class="col-12 col-lg-9">
	            	<br>
	            	<form action="{% url 'posts:video_search' %}" method="POST">
	            	    {% csrf_token %}
	            	    <table border="0" class="col-12">
	            	        <tr>
	            	            <td>
	            	                <input type="text" name="search" class="form-control col-12 col-lg-12" placeholder="Search selected source by keyword..." value="" required>
	            	            </td>
	            	            <td>
	            	                <select name="video_type" class="form-control col-12 col-lg-10" required>
	            	                    <option value="">Select source</option>
	            	                    <option value="">-----------</option>
	            	                    <option value="linked">Linked Videos</option>
	            	                    <option value="local">Local Videos</option>
	            	                </select>
	            	            </td>
	            	            <td>
	            	                <input type="submit" value="Search" class="btn btn-primary col-12 col-lg-9">
	            	            <td>
	            	        </tr>
	            	    </table>
	            	</form>
	            	<br>
	            	<br>
	                <div class="intro-news-tab">
	                	<!-- Intro News Filter -->
	                	<div class="intro-news-filter d-flex justify-content-between">
	                	    	{% if local_video_single %}
	                	    		<h3>{{ local_video_single.title }}</h3>
	                	    	{% endif %}
	                	    <nav>
	                	        <div class="nav nav-tabs" id="nav-tab" role="tablist">
	                	            <a class="nav-item nav-link active" href="{% url 'posts:videos' %}" role="tab" aria-controls="nav-1" aria-selected="true">Home Videos</a>
	                	        </div>
	                	    </nav>
	                	</div>

	                    <div class="tab-content" id="nav-tabContent">
	                    	{% if local_video_single %}
								<video width="820" height="470" controls="true" poster="{{ local_video_single.image.url }}">
						            <source src="{{ local_video_single.local_video_file.url }}" type="video/mp4" loop="true">
						        </video>
						       	<p>{{ local_video_single.text }}</p>
							{% else %}
								<br>
								<center><h6><font color='orange'>Hmm... Something went wrong or the video is not available!</font></h6></center>
							{% endif %}
	                    </div>
	                </div>
	            </div>

	            <!-- Sidebar Widget -->
	            <div class="col-12 col-sm-9 col-md-6 col-lg-3">
	            	<!-- Add Widget -->
                    <div class="single-widget-area add-widget mb-30">
                    	<!-- Single News Area -->
                    	{% if sidebar_related_videos %}
                    		{% for side_video in sidebar_related_videos %}
                    			{% if forloop.counter <= 10 %}
			                    	<div class="single-blog-post style-2 mb-5">
			                    	    <!-- Blog Thumbnail -->
			                    	    <div class="blog-thumbnail">
			                    	        <a href="{% url 'posts:local_video_player' side_video.id %}"><img src="{{ side_video.image.url }}" alt=""></a>
			                    	    </div>

			                    	    <!-- Blog Content -->
			                    	    <div class="blog-content">
                                            <span class="post-date">{{ side_video.published_date|date:"F j, Y" }}</span>
                                             <a href="{% url 'posts:local_video_player' side_video.id %}" class="post-title video-btn">{{ side_video.title }}</a>
                                            <a href="{% url 'posts:local_video_player' side_video.id %}" class="post-author video-btn">By {{ side_video.author }}</a>
                                        </div>
			                    	</div>
			            		{% endif %}
                        	{% endfor %}
                        {% endif %}
                    </div>
	            </div>
	        </div>
	    </div>
	</section>
	<!-- ##### Intro News Area End ##### -->
	 <!-- ##### Add Area Start ##### -->
    <div class="big-add-area mb-100">
        <div class="container-fluid">
            {% if bottom_ad %}
                {% for i in bottom_ad %}
                    <a href="{{ i.ad_link }}">
                        <img src="{{ i.ad.url }}" alt="">
                    </a>
                {% endfor %}
            {% endif %}
        </div>
    </div>

{% endblock %}

posts/templates/posts/photos.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  Photos
{% endblock %}


{% block content %}

    <!-- ##### Top News Area Start ##### -->
    <div class="top-news-area section-padding-100">
        <div class="container">
            <div class="row">

                <!-- Single News Area -->
                {% if listings_6 %}
                    {% for list in listings_6 %}
                        <div class="col-12 col-sm-6 col-lg-4">
                            <div class="single-blog-post style-2 mb-5">
                                <!-- Blog Thumbnail -->
                                <div class="blog-thumbnail">
                                    <a href="#"><img src="{{ list.image.url }}" alt=""></a>
                                </div>

                                <!-- Blog Content -->
                                <div class="blog-content">
                                    <span class="post-date">{{ list.published_date|date:"F j, Y" }}</span>
                                    <a href="#" class="post-title">{{ list.title }}</a>
                                    <a href="#" class="post-author">By {{ list.author }}</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% else %}
                        <h1>No Photos Found!</h1>
                    {% endif %}

                <div class="col-12">
                    <div class="load-more-button text-center">
                        <a href="#" class="btn newsbox-btn">Load More</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- ##### Top News Area End ##### -->


    
    <div class="big-add-area">
        <div class="container-fluid">
            <a href="#"><img src="{% static 'img/bg-img/add4.png' %}" alt=""></a>
        </div>
    </div>
    <!-- ##### Add Area End ##### -->


{% endblock %}

posts/templates/posts/posts.html
{% extends 'base.html' %}

{% load static %}
{% load ads_tags %}

{% block title %}
  Resources and Contents
{% endblock %}


{% block content %}

    <!-- ##### Catagory Featured Area Start ##### -->
    {% if cover_page %}
        {% for cover in cover_page %}
            <div class="catagory-featured-post bg-overlay clearfix" style="background-image: url({{ cover.top_cover_image.url  }})">
                <div class="container-fluid h-100">
                    <div class="row h-100 align-items-center">
                        <div class="col-12 col-lg-9">
                            <!-- Post Content -->
                            <div class="post-content">
                                <!--<p class="tag"><span>Entertainment</span></p>-->
                                <a class="post-title">{{ cover.title }}</a>
                                <br>
                                <p>{{ cover.text }}</p>
                                <span class="post-date">{{ cover.created_at | date }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <!-- ##### Catagory Featured Area End ##### -->




	<!-- ##### News Area Start ##### -->
    <div class="news-area section-padding-100-70">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-8 col-lg-8">
                    <!-- Single News Area -->
                    <div class="single-blog-post d-flex flex-wrap style-5 mb-30">
                        <!-- Blog Thumbnail -->
                        {% if cover_page %}
                            {% for cover in cover_page %}
                                <div class="blog-thumbnail">
                                    <a href="{% url 'posts:videos' %}"><img src="{{ cover.video_tag_image.url }}" alt=""></a>
                                </div>
                                <!-- Blog Content -->
                                <div class="blog-content">
                                    <a href="{% url 'posts:videos' %}" class="post-title">{{ cover.video_tag_title }}</a>
                                    <p>{{ cover.video_tag_text }}</p>
                                    <span class="post-date">Updated on {{ cover.created_at }}</span>
                                </div>
                            {% endfor %}
                        {% endif %}
                        <h1><a href="{% url 'posts:videos' %}" class="btn newsbox-btn m-2">Videos</a></h1>
                    </div>
                    <hr>

                    <!-- Single News Area -->
                    <div class="single-blog-post d-flex flex-wrap style-5 mb-30">
                        <!-- Blog Thumbnail -->
                        {% if cover_page %}
                            {% for cover in cover_page %}
                                <div class="blog-thumbnail">
                                    <a href="{% url 'blogs:post_list' %}"><img src="{{ cover.blog_article_tag_image.url }}" alt=""></a>
                                </div>
                                <!-- Blog Content -->
                                <div class="blog-content">
                                    <a href="{% url 'blogs:post_list' %}" class="post-title">{{ cover.blog_article_tag_title }}</a>
                                    <p>{{ cover.blog_article_tag_text }}</p>
                                    <span class="post-date">Updated on {{ cover.created_at }}</span>
                                </div>
                            {% endfor %}
                        {% endif %}
                        <h1><a href="{% url 'blogs:post_list' %}" class="btn newsbox-btn m-2">Blogs and Articles</a></h1>
                    </div>
                    <hr>

                </div>
                <!-- Sidebar Widget -->
                <div class="col-12 col-sm-9 col-md-6 col-lg-4">
                    {% include 'visits/sidebar.html' %}
                </div>
            </div>
        </div>
    </div>
    <!-- ##### News Area End ##### -->


{% endblock %}